name: Upload Docker Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: |
          echo ${{ github.sha }}
          git checkout ${{ github.sha }}
          echo "COMMIT_ID=$(echo ${{ github.sha }})" >> $GITHUB_ENV
    - name: Create config file
      run: |
          touch cmd/whatisthissong/config/config.conf
          echo "$CONFIG_CONF" >> cmd/whatisthissong/config/config.conf
          echo "create config.conf successfully"
      env:
          CONFIG_CONF: ${{ secrets.CONFIG_CONF }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
  
    - name: Build & Push the Docker image
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{github.repository_owner}}/whatisthissong:latest
          build-args: |
            commit_id=${{ github.event.head_commit.id }}
