name: Upload Docker Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: |
          echo ${{ github.sha }}
          git checkout ${{ github.sha }}
          echo "COMMIT_ID=$(echo ${{ github.sha }})" >> $GITHUB_ENV
    - name: Create config file
      run: |
          touch cmd/whatisthissong/config/config.conf
          echo "$CONFIG_CONF" >> cmd/whatisthissong/config/config.conf
          echo "create config.conf successfully"
      env:
          CONFIG_CONF: ${{ secrets.CONFIG_CONF }}
    - name: set lower case owner name
      run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      env:
          OWNER: '${{ github.repository_owner }}'
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.CR_PAT }}
      env:
          OWNER_LC: ${{ env.OWNER_LC }}
  
    - name: Build & Push the Docker image
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/whatisthissong:latest
          build-args: |
            commit_id=${{ github.event.head_commit.id }}
      env:
          OWNER_LC: ${{ env.OWNER_LC }}
